server {
    listen 80;
    listen [::]:80;
    server_name houssk.fr www.houssk.fr;

    root /var/www/houssk-site/current/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico|webp|avif|woff2?)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }
}
